/**
 * Country → state/region → city tree for listing location selects.
 * "Other" allows free-text state/city outside this tree.
 */

export const LISTING_COUNTRIES = [
  'Qatar',
  'United Arab Emirates',
  'Saudi Arabia',
  'Kuwait',
  'Bahrain',
  'Oman',
  'Sri Lanka',
  'India',
  'Pakistan',
  'Bangladesh',
  'Egypt',
  'United Kingdom',
  'United States',
  'Canada',
  'Australia',
  'Germany',
  'France',
  'Turkey',
  'Other',
] as const;

export type ListingCountry = (typeof LISTING_COUNTRIES)[number];

/** country → states/regions */
export const STATES_BY_COUNTRY: Record<string, string[]> = {
  Qatar: [
    'Doha',
    'Al Rayyan',
    'Al Wakrah',
    'Al Khor',
    'Umm Salal',
    'Al Daayen',
    'Al Shamal',
    'Al Shahaniya',
  ],
  'United Arab Emirates': [
    'Dubai',
    'Abu Dhabi',
    'Sharjah',
    'Ajman',
    'Ras Al Khaimah',
    'Fujairah',
    'Umm Al Quwain',
  ],
  'Saudi Arabia': [
    'Riyadh',
    'Makkah',
    'Madinah',
    'Eastern Province',
    'Asir',
    'Tabuk',
    'Qassim',
    'Hail',
    'Jazan',
    'Najran',
  ],
  Kuwait: ['Capital', 'Hawalli', 'Farwaniya', 'Ahmadi', 'Jahra', 'Mubarak Al-Kabeer'],
  Bahrain: ['Capital', 'Muharraq', 'Northern', 'Southern'],
  Oman: ['Muscat', 'Dhofar', 'Al Batinah North', 'Al Batinah South', 'Ad Dakhiliyah', 'Ash Sharqiyah'],
  'Sri Lanka': [
    'Western',
    'Central',
    'Southern',
    'Northern',
    'Eastern',
    'North Western',
    'North Central',
    'Uva',
    'Sabaragamuwa',
  ],
  India: [
    'Maharashtra',
    'Delhi',
    'Karnataka',
    'Tamil Nadu',
    'Telangana',
    'Gujarat',
    'West Bengal',
    'Kerala',
    'Rajasthan',
    'Uttar Pradesh',
  ],
  Pakistan: ['Punjab', 'Sindh', 'Khyber Pakhtunkhwa', 'Balochistan', 'Islamabad Capital Territory'],
  Bangladesh: ['Dhaka', 'Chattogram', 'Khulna', 'Rajshahi', 'Sylhet', 'Barishal', 'Rangpur', 'Mymensingh'],
  Egypt: ['Cairo', 'Giza', 'Alexandria', 'Dakahlia', 'Sharqia', 'Qalyubia', 'Gharbia', 'Red Sea'],
  'United Kingdom': ['England', 'Scotland', 'Wales', 'Northern Ireland'],
  'United States': [
    'California',
    'Texas',
    'Florida',
    'New York',
    'Illinois',
    'Pennsylvania',
    'Ohio',
    'Georgia',
    'North Carolina',
    'Michigan',
    'Washington',
    'Massachusetts',
  ],
  Canada: ['Ontario', 'Quebec', 'British Columbia', 'Alberta', 'Manitoba', 'Saskatchewan', 'Nova Scotia'],
  Australia: [
    'New South Wales',
    'Victoria',
    'Queensland',
    'Western Australia',
    'South Australia',
    'Tasmania',
    'Australian Capital Territory',
    'Northern Territory',
  ],
  Germany: [
    'Bavaria',
    'Berlin',
    'Hamburg',
    'Hesse',
    'Lower Saxony',
    'North Rhine-Westphalia',
    'Baden-Württemberg',
    'Saxony',
  ],
  France: [
    'Île-de-France',
    'Auvergne-Rhône-Alpes',
    'Provence-Alpes-Côte d\'Azur',
    'Occitanie',
    'Nouvelle-Aquitaine',
    'Hauts-de-France',
    'Grand Est',
  ],
  Turkey: ['Istanbul', 'Ankara', 'Izmir', 'Antalya', 'Bursa', 'Adana', 'Gaziantep', 'Konya'],
};

/** `${country}|${state}` → cities */
export const CITIES_BY_STATE: Record<string, string[]> = {
  'Qatar|Doha': ['West Bay', 'The Pearl', 'Al Sadd', 'Old Airport', 'Bin Mahmoud', 'Musheireb', 'Katara'],
  'Qatar|Al Rayyan': ['Education City', 'Aspire Zone', 'Al Gharrafa', 'Muaither', 'Ain Khaled'],
  'Qatar|Al Wakrah': ['Al Wukair', 'Mesaieed', 'Al Thakhira'],
  'Qatar|Al Khor': ['Al Thakhira', 'Al Khor City'],
  'Qatar|Umm Salal': ['Umm Salal Mohammed', 'Umm Salal Ali'],
  'Qatar|Al Daayen': ['Lusail', 'Al Kheesa', 'Wadi Al Banat'],
  'Qatar|Al Shamal': ['Madinat ash Shamal', 'Ar Ru\'ays'],
  'Qatar|Al Shahaniya': ['Al Shahaniya City', 'Dukhan'],
  'United Arab Emirates|Dubai': ['Downtown', 'Marina', 'Jumeirah', 'Deira', 'Business Bay', 'JLT'],
  'United Arab Emirates|Abu Dhabi': ['Corniche', 'Al Reem Island', 'Yas Island', 'Khalifa City'],
  'United Arab Emirates|Sharjah': ['Al Majaz', 'Al Khan', 'University City'],
  'United Arab Emirates|Ajman': ['Ajman City', 'Al Nuaimiya'],
  'United Arab Emirates|Ras Al Khaimah': ['Al Nakheel', 'Al Hamra'],
  'United Arab Emirates|Fujairah': ['Fujairah City', 'Dibba'],
  'United Arab Emirates|Umm Al Quwain': ['UAQ City', 'Falaj Al Mualla'],
  'Saudi Arabia|Riyadh': ['Riyadh City', 'Diriyah', 'Al Kharj'],
  'Saudi Arabia|Makkah': ['Jeddah', 'Mecca', 'Taif'],
  'Saudi Arabia|Madinah': ['Medina', 'Yanbu'],
  'Saudi Arabia|Eastern Province': ['Dammam', 'Khobar', 'Dhahran', 'Jubail', 'Al Ahsa'],
  'Saudi Arabia|Asir': ['Abha', 'Khamis Mushait'],
  'Saudi Arabia|Tabuk': ['Tabuk City', 'Duba'],
  'Saudi Arabia|Qassim': ['Buraidah', 'Unaizah'],
  'Saudi Arabia|Hail': ['Hail City'],
  'Saudi Arabia|Jazan': ['Jazan City', 'Sabya'],
  'Saudi Arabia|Najran': ['Najran City'],
  'Kuwait|Capital': ['Kuwait City', 'Sharq', 'Dasman'],
  'Kuwait|Hawalli': ['Hawalli', 'Salmiya', 'Jabriya'],
  'Kuwait|Farwaniya': ['Farwaniya', 'Khaitan', 'Jleeb'],
  'Kuwait|Ahmadi': ['Ahmadi', 'Fahaheel', 'Mangaf'],
  'Kuwait|Jahra': ['Jahra', 'Sulaibiya'],
  'Kuwait|Mubarak Al-Kabeer': ['Sabah Al Salem', 'Qurain'],
  'Bahrain|Capital': ['Manama', 'Juffair', 'Seef'],
  'Bahrain|Muharraq': ['Muharraq', 'Busaiteen', 'Hidd'],
  'Bahrain|Northern': ['Budaiya', 'Hamala', 'Janabiya'],
  'Bahrain|Southern': ['Riffa', 'Isa Town', 'Awali'],
  'Oman|Muscat': ['Muscat', 'Muttrah', 'Qurum', 'Al Khuwair', 'Seeb'],
  'Oman|Dhofar': ['Salalah', 'Taqah'],
  'Oman|Al Batinah North': ['Sohar', 'Shinas'],
  'Oman|Al Batinah South': ['Barka', 'Rustaq'],
  'Oman|Ad Dakhiliyah': ['Nizwa', 'Bahla'],
  'Oman|Ash Sharqiyah': ['Sur', 'Ibra'],
  'Sri Lanka|Western': ['Colombo', 'Dehiwala', 'Moratuwa', 'Negombo', 'Gampaha', 'Kalutara'],
  'Sri Lanka|Central': ['Kandy', 'Matale', 'Nuwara Eliya'],
  'Sri Lanka|Southern': ['Galle', 'Matara', 'Hambantota'],
  'Sri Lanka|Northern': ['Jaffna', 'Vavuniya', 'Mannar'],
  'Sri Lanka|Eastern': ['Trincomalee', 'Batticaloa', 'Ampara'],
  'Sri Lanka|North Western': ['Kurunegala', 'Puttalam'],
  'Sri Lanka|North Central': ['Anuradhapura', 'Polonnaruwa'],
  'Sri Lanka|Uva': ['Badulla', 'Monaragala'],
  'Sri Lanka|Sabaragamuwa': ['Ratnapura', 'Kegalle'],
  'India|Maharashtra': ['Mumbai', 'Pune', 'Nagpur', 'Thane', 'Nashik'],
  'India|Delhi': ['New Delhi', 'Dwarka', 'Rohini', 'Saket'],
  'India|Karnataka': ['Bengaluru', 'Mysuru', 'Mangaluru', 'Hubli'],
  'India|Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli'],
  'India|Telangana': ['Hyderabad', 'Warangal', 'Nizamabad'],
  'India|Gujarat': ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot'],
  'India|West Bengal': ['Kolkata', 'Howrah', 'Durgapur'],
  'India|Kerala': ['Kochi', 'Thiruvananthapuram', 'Kozhikode'],
  'India|Rajasthan': ['Jaipur', 'Jodhpur', 'Udaipur'],
  'India|Uttar Pradesh': ['Lucknow', 'Kanpur', 'Noida', 'Varanasi'],
  'Pakistan|Punjab': ['Lahore', 'Faisalabad', 'Rawalpindi', 'Multan', 'Gujranwala'],
  'Pakistan|Sindh': ['Karachi', 'Hyderabad', 'Sukkur'],
  'Pakistan|Khyber Pakhtunkhwa': ['Peshawar', 'Mardan', 'Abbottabad'],
  'Pakistan|Balochistan': ['Quetta', 'Gwadar'],
  'Pakistan|Islamabad Capital Territory': ['Islamabad'],
  'Bangladesh|Dhaka': ['Dhaka', 'Gazipur', 'Narayanganj'],
  'Bangladesh|Chattogram': ['Chattogram', 'Cox\'s Bazar'],
  'Bangladesh|Khulna': ['Khulna', 'Jessore'],
  'Bangladesh|Rajshahi': ['Rajshahi', 'Bogra'],
  'Bangladesh|Sylhet': ['Sylhet', 'Moulvibazar'],
  'Bangladesh|Barishal': ['Barishal'],
  'Bangladesh|Rangpur': ['Rangpur', 'Dinajpur'],
  'Bangladesh|Mymensingh': ['Mymensingh'],
  'Egypt|Cairo': ['Cairo', 'Nasr City', 'Heliopolis', 'Maadi'],
  'Egypt|Giza': ['Giza', '6th of October', 'Sheikh Zayed'],
  'Egypt|Alexandria': ['Alexandria', 'Montaza'],
  'Egypt|Dakahlia': ['Mansoura', 'Talkha'],
  'Egypt|Sharqia': ['Zagazig', '10th of Ramadan'],
  'Egypt|Qalyubia': ['Banha', 'Shubra El Kheima'],
  'Egypt|Gharbia': ['Tanta', 'El Mahalla'],
  'Egypt|Red Sea': ['Hurghada', 'El Gouna'],
  'United Kingdom|England': ['London', 'Manchester', 'Birmingham', 'Leeds', 'Liverpool', 'Bristol'],
  'United Kingdom|Scotland': ['Edinburgh', 'Glasgow', 'Aberdeen', 'Dundee'],
  'United Kingdom|Wales': ['Cardiff', 'Swansea', 'Newport'],
  'United Kingdom|Northern Ireland': ['Belfast', 'Derry', 'Lisburn'],
  'United States|California': ['Los Angeles', 'San Francisco', 'San Diego', 'San Jose', 'Sacramento'],
  'United States|Texas': ['Houston', 'Dallas', 'Austin', 'San Antonio', 'Fort Worth'],
  'United States|Florida': ['Miami', 'Orlando', 'Tampa', 'Jacksonville'],
  'United States|New York': ['New York City', 'Buffalo', 'Rochester', 'Albany'],
  'United States|Illinois': ['Chicago', 'Aurora', 'Naperville'],
  'United States|Pennsylvania': ['Philadelphia', 'Pittsburgh', 'Allentown'],
  'United States|Ohio': ['Columbus', 'Cleveland', 'Cincinnati'],
  'United States|Georgia': ['Atlanta', 'Savannah', 'Augusta'],
  'United States|North Carolina': ['Charlotte', 'Raleigh', 'Durham'],
  'United States|Michigan': ['Detroit', 'Grand Rapids', 'Ann Arbor'],
  'United States|Washington': ['Seattle', 'Spokane', 'Tacoma'],
  'United States|Massachusetts': ['Boston', 'Cambridge', 'Worcester'],
  'Canada|Ontario': ['Toronto', 'Ottawa', 'Mississauga', 'Hamilton'],
  'Canada|Quebec': ['Montreal', 'Quebec City', 'Laval'],
  'Canada|British Columbia': ['Vancouver', 'Victoria', 'Surrey'],
  'Canada|Alberta': ['Calgary', 'Edmonton', 'Red Deer'],
  'Canada|Manitoba': ['Winnipeg', 'Brandon'],
  'Canada|Saskatchewan': ['Saskatoon', 'Regina'],
  'Canada|Nova Scotia': ['Halifax', 'Sydney'],
  'Australia|New South Wales': ['Sydney', 'Newcastle', 'Wollongong'],
  'Australia|Victoria': ['Melbourne', 'Geelong', 'Ballarat'],
  'Australia|Queensland': ['Brisbane', 'Gold Coast', 'Cairns'],
  'Australia|Western Australia': ['Perth', 'Fremantle'],
  'Australia|South Australia': ['Adelaide'],
  'Australia|Tasmania': ['Hobart', 'Launceston'],
  'Australia|Australian Capital Territory': ['Canberra'],
  'Australia|Northern Territory': ['Darwin', 'Alice Springs'],
  'Germany|Bavaria': ['Munich', 'Nuremberg', 'Augsburg'],
  'Germany|Berlin': ['Berlin'],
  'Germany|Hamburg': ['Hamburg'],
  'Germany|Hesse': ['Frankfurt', 'Wiesbaden', 'Darmstadt'],
  'Germany|Lower Saxony': ['Hanover', 'Braunschweig'],
  'Germany|North Rhine-Westphalia': ['Cologne', 'Düsseldorf', 'Dortmund', 'Essen'],
  'Germany|Baden-Württemberg': ['Stuttgart', 'Mannheim', 'Karlsruhe'],
  'Germany|Saxony': ['Dresden', 'Leipzig'],
  'France|Île-de-France': ['Paris', 'Versailles', 'Boulogne-Billancourt'],
  'France|Auvergne-Rhône-Alpes': ['Lyon', 'Grenoble', 'Saint-Étienne'],
  'France|Provence-Alpes-Côte d\'Azur': ['Marseille', 'Nice', 'Toulon'],
  'France|Occitanie': ['Toulouse', 'Montpellier'],
  'France|Nouvelle-Aquitaine': ['Bordeaux', 'Limoges'],
  'France|Hauts-de-France': ['Lille', 'Amiens'],
  'France|Grand Est': ['Strasbourg', 'Nancy', 'Reims'],
  'Turkey|Istanbul': ['Istanbul', 'Kadıköy', 'Beşiktaş', 'Üsküdar'],
  'Turkey|Ankara': ['Ankara', 'Çankaya'],
  'Turkey|Izmir': ['Izmir', 'Konak', 'Bornova'],
  'Turkey|Antalya': ['Antalya', 'Alanya', 'Side'],
  'Turkey|Bursa': ['Bursa', 'Nilüfer'],
  'Turkey|Adana': ['Adana'],
  'Turkey|Gaziantep': ['Gaziantep'],
  'Turkey|Konya': ['Konya'],
};

export const stateKey = (country: string, state: string): string => `${country}|${state}`;

export const getStatesForCountry = (country: string): string[] => STATES_BY_COUNTRY[country] ?? [];

export const getCitiesForState = (country: string, state: string): string[] =>
  CITIES_BY_STATE[stateKey(country, state)] ?? [];

export const isStructuredCountry = (country: string): boolean =>
  country !== 'Other' && Boolean(STATES_BY_COUNTRY[country]?.length);
